#############
### build ###
#############

# base image
FROM node:12.2.0 as build


# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@9.0.0

# add app
COPY . /app

# run tests
RUN ng test --watch=false
#RUN ng e2e --port 4202

# generate build
RUN ng build --prod --output-path=dist

############
### prod ###
############

# base image
FROM nginx:1.16.0-alpine

RUN apk --no-cache add gettext
# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# When the container starts, replace the env.js with values from environment variables

# expose port 80
EXPOSE 80

# run nginx
ENTRYPOINT ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]

RUN cat /usr/share/nginx/html/assets/env.js
